//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaModelo.ModeloFacturacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DominioEntidades.ModeloFacturacion;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class db_facturacion_entities : DbContext
    {
        public db_facturacion_entities()
            : base("name=db_facturacion_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<producto> producto { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<formularios> formularios { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    
        public virtual ObjectResult<producto> SPWB_GetListProductos(string con)
        {
            var conParameter = con != null ?
                new ObjectParameter("con", con) :
                new ObjectParameter("con", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<producto>("SPWB_GetListProductos", conParameter);
        }
    
        public virtual ObjectResult<producto> SPWB_GetListProductos(string con, MergeOption mergeOption)
        {
            var conParameter = con != null ?
                new ObjectParameter("con", con) :
                new ObjectParameter("con", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<producto>("SPWB_GetListProductos", mergeOption, conParameter);
        }
    }
}
